apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: players-service-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: players-service
    spec:
      containers:
      - image: <repo name>/players-service
        # env:
        # - name: ENV_NAME
        #   value: env_value
        name: players-service
        ports:
         - containerPort: 3000
        livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 40
            timeoutSeconds: 4  
        resources:
          requests:
            cpu: 500m # min cpu usage - important for limiting num pods in single machine
      restartPolicy: Always
      terminationGracePeriodSeconds: 30  #gracefull shutdown
---
kind: Service
apiVersion: v1
metadata:
  name: players-service
spec:
  type: LoadBalancer
  selector:
    app: players-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000

